# Site settings
title: Kevin Hwang
email: k3vinhwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kevin Hwang's personal website!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kevinhwang.net" # the base hostname & protocol for your site
twitter_username: k3vinhwang
github_username:  khwang

# Build settings
markdown: kramdown
